settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Steven Evans # [First Name(s)] [Last Name]
  links:
    # LinkedIn
    - https://www.linkedin.com/posts/activity-7222799261837451264-5VhT/?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_gradient-descent-the-learning-rate-and-activity-7240948924230868992-6M8y?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_ai-notes-initializing-neural-networks-activity-7244010847885271040-V7JT?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_github-sflyrangerneuralnetworksprojects-activity-7247393263920291840-4sbi?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_beyourself-believe-grow-activity-7253546673879068672-7GCg?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_ai-machinelearning-naturallanguageprocessing-activity-7260867223873822720-zJsm?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_github-sflyrangersafe-model-integration-activity-7263736015138234369-nmHZ?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_managing-bias-and-variance-activity-7264143803450564609-Os5I?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_transformer-explainer-llm-transformer-model-activity-7270275450935926784-1JNA?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/steven-evansed_im-thrilled-to-share-a-project-i-worked-activity-7280598747342893058-uhei?utm_source=share&utm_medium=member_desktop
    # Github
    - https://github.com/sflyranger/LLM-twin-from-scratch
    - https://github.com/sflyranger/finetuning-encoder-decoder-models-sequence-classification
    - https://github.com/sflyranger/private-files
    - https://github.com/sflyranger/Snowflake-datawarehousing
    - https://github.com/sflyranger/summarization_experiments
    - https://github.com/sflyranger/ML_baseline_training_pipelines
    - https://github.com/sflyranger/safe-model-integration
    - https://github.com/sflyranger/Simple_Rag_Pipeline
    - https://github.com/sflyranger/multilabel_classification_nns
    - https://github.com/sflyranger/Basic_R_Projects
    - https://github.com/sflyranger/Neural_Network_Practice
    - https://github.com/sflyranger/Spam-Detection-Pipelines-
    - https://github.com/sflyranger/Stock_Price_Machine_Learning_Project
    - https://github.com/sflyranger/Python-Projects
    - https://github.com/sflyranger/SQL_Basic_Projects