settings:
  docker:
    parent_image: 009717615422.dkr.ecr.us-east-1.amazonaws.com/zenml-jggvwy:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  author_full_names:
    - Steven Evans
